-- File: dev_auth_users.sql
-- Purpose: Create local development users for JWT login smoke testing.
-- Run after database migrations and dev_sample_data.sql.
-- Development passwords:
--   admin@example.com / Admin@123456
--   owner@example.com / Owner@123456
-- Password hashes are bcrypt hashes generated by the API bcrypt dependency.

INSERT INTO users (id, full_name, phone, email, password_hash, preferred_language, is_active)
VALUES
  (
    '00000000-0000-0000-0000-000000000201',
    'Development Super Admin',
    '+94770000001',
    'admin@example.com',
    '$2b$12$lr/iwSGDMAS3v0oF5oGOOOgvFy.wp7qxmJMKzKVuxZZpqvm.AQquq',
    'en',
    true
  ),
  (
    '00000000-0000-0000-0000-000000000202',
    'Development Business Owner',
    '+94770000002',
    'owner@example.com',
    '$2b$12$gLbY9eax3VEPmWvZAQKjjehypdHpHnyh00j2Ira10rNlO.pcuISem',
    'en',
    true
  )
ON CONFLICT (id) DO UPDATE SET
  password_hash = EXCLUDED.password_hash,
  is_active = EXCLUDED.is_active,
  updated_at = now();

INSERT INTO business_users (business_id, user_id, role, is_active)
SELECT
  '00000000-0000-0000-0000-000000000101',
  '00000000-0000-0000-0000-000000000201',
  'SUPER_ADMIN',
  true
WHERE EXISTS (SELECT 1 FROM businesses WHERE id = '00000000-0000-0000-0000-000000000101')
ON CONFLICT (business_id, user_id, role) DO NOTHING;

INSERT INTO business_users (business_id, user_id, role, is_active)
SELECT
  '00000000-0000-0000-0000-000000000101',
  '00000000-0000-0000-0000-000000000202',
  'BUSINESS_OWNER',
  true
WHERE EXISTS (SELECT 1 FROM businesses WHERE id = '00000000-0000-0000-0000-000000000101')
ON CONFLICT (business_id, user_id, role) DO NOTHING;
