export enum AppointmentStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RESCHEDULE_PROPOSED = 'RESCHEDULE_PROPOSED',
  RESCHEDULE_ACCEPTED = 'RESCHEDULE_ACCEPTED',
  RESCHEDULE_REJECTED = 'RESCHEDULE_REJECTED',
  CANCELLED_BY_CUSTOMER = 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_OPERATOR = 'CANCELLED_BY_OPERATOR',
  DELAYED = 'DELAYED',
  IN_QUEUE = 'IN_QUEUE',
  IN_SERVICE = 'IN_SERVICE',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW'
}