export enum BusinessType {
  MEDICAL_CENTER = 'MEDICAL_CENTER',
  DOCTOR = 'DOCTOR',
  CLINIC = 'CLINIC',
  HOSPITAL = 'HOSPITAL',
  BARBER_SHOP = 'BARBER_SHOP',
  BEAUTY_PARLOUR = 'BEAUTY_PARLOUR',
  SALON = 'SALON',
  SERVICE_SHOP = 'SERVICE_SHOP',
  OTHER = 'OTHER'
}