export enum QueueStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  WAITING = 'WAITING',
  CALLED = 'CALLED',
  IN_SERVICE = 'IN_SERVICE',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW'
}