export enum TemplateKey {
  QUEUE_CONFIRMED = 'QUEUE_CONFIRMED',
  QUEUE_POSITION_UPDATED = 'QUEUE_POSITION_UPDATED',
  APPOINTMENT_PENDING_APPROVAL = 'APPOINTMENT_PENDING_APPROVAL',
  APPOINTMENT_APPROVED = 'APPOINTMENT_APPROVED',
  APPOINTMENT_REJECTED = 'APPOINTMENT_REJECTED',
  APPOINTMENT_CANCELLED_BY_CUSTOMER = 'APPOINTMENT_CANCELLED_BY_CUSTOMER',
  RESCHEDULE_PROPOSED = 'RESCHEDULE_PROPOSED',
  DELAY_NOTICE = 'DELAY_NOTICE',
  NO_SHOW_WARNING = 'NO_SHOW_WARNING',
  ONLINE_BOOKING_BANNED = 'ONLINE_BOOKING_BANNED',
  BAN_RESET = 'BAN_RESET'
}