export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  MANAGER = 'MANAGER',
  DOCTOR = 'DOCTOR',
  OPERATOR = 'OPERATOR',
  STAFF = 'STAFF',
  CUSTOMER = 'CUSTOMER'
}